#!/usr/bin/env bash
# Function to display information about subdomains
display_subdomain_info() {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        echo -n "The subdomain $sub is a"
        dig_result=$(dig "$sub.$domain" | awk '/ANSWER SECTION/ {getline; print}')
        record_type=$(echo "$dig_result" | awk '{print $4}')
        destination=$(echo "$dig_result" | awk '{print $5}')
        echo " $record_type record and points to $destination"
    done
}

# Main script starts here
if [ "$#" -eq 1 ]; then
    domain="$1"
    display_subdomain_info "$domain"
elif [ "$#" -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    display_subdomain_info "$domain" "$subdomain"
else
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi
