#!/usr/bin/env bash
#!/bin/bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Create a redirection configuration file
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/redirect

# Activate the configuration by creating a symlink
ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Test Nginx configuration
nginx -t

# Restart Nginx to apply changes
service nginx restart

