#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create index.html file with content "Holberton School"
echo "Holberton School" | sudo tee /var/www/html/index.html

# Configure Nginx to redirect /redirect_me to a YouTube video
new_string="listen 80 default_server;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=xJJsoquu70o permanent;"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-available/default

# Create custom 404 page with content "Ceci n'est pas une page"
echo "Ceci n'est pas une page\n" | sudo tee /var/www/html/404.html

# Configure Nginx to serve the custom 404 page
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
sudo service nginx restart

