#!/usr/bin/env bash

# Configure Nginx to include a custom header in the HTTP response
var=$(hostname)
new_string="error_page 404 /custom_404.html;\n location /redirect_me {\n return 301 \$scheme://www.google.com;}"
new_string2="server {\n\tadd_header X-Served-By $var;"

# Update package list
apt-get update -y

# Install Nginx
apt-get install nginx -y

# Create index.html with "Hello World!" content
echo "Hello World!" > /usr/share/nginx/html/index.html

# Create custom_404.html
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Modify Nginx default configuration to include custom header
sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

# Verify that the X-Served-By header is added to the response
curl -sI localhost | grep "X-Served-By: $var" >/dev/null && echo "Custom header X-Served-By is present" || echo "Custom header X-Served-By is not present"

