#!/usr/bin/env bash
# Changes the port configuration in Nginx from 8080 to 80 and restarts the Nginx service

# Update Nginx configuration to change port 8080 to 80
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/g' /etc/nginx/sites-available/default
# Restart Nginx service to apply changes
sudo service nginx restart


# Enable Nginx to start on boot
sudo systemctl enable nginx
