#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

# Copy the current hosts file to a new file
cp /etc/hosts ~/hosts.new

# Update the new hosts file with the desired configurations
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new

# Replace the system's hosts file with the updated version
cp -f ~/hosts.new /etc/hosts

