#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

# Copy the current hosts file to a new file
# Server configuration
sudo cp /etc/hosts ~/hosts.new
sudo sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo "8.8.8.8   facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
